### ISSUE TITLE
调用新建文件夹和上传文件接口都失败?

### ISSUE THREAD

**Issue by zzti** [dorisoy/Dorisoy.Pan#27]
![搜狗截图20240104104609](https://github.com/dorisoy/Dorisoy.Pan/assets/5188183/000e18d5-b262-42a3-9a5c-99c56fe3d0cf)
单独调用swagger接口，也返回401错误，是不是需要特殊授权配置？
Curl

curl -X 'POST' \
  'https://localhost:44314/api/Folder/folder/6bbf4778-b9b4-417d-87c4-61985648bd77' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json-patch+json' \
  -d '{
  "virtualFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "physicalFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "paths": [
    "string"
  ]
}'
Request URL
https://localhost:44314/api/Folder/folder/6bbf4778-b9b4-417d-87c4-61985648bd77
Server response
![搜狗截图20240104112020](https://github.com/dorisoy/Dorisoy.Pan/assets/5188183/7643c60c-3ee7-409d-934e-a468d874aa69)

**Comment by dorisoy** [comment]
> ![搜狗截图20240104104609](https://private-user-images.githubusercontent.com/5188183/294076731-000e18d5-b262-42a3-9a5c-99c56fe3d0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzQyMTUsIm5iZiI6MTcwNDQzMzkxNSwicGF0aCI6Ii81MTg4MTgzLzI5NDA3NjczMS0wMDBlMThkNS1iMjYyLTQyYTMtOWE1Yy05OWM1NmZlM2QwY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDU1MTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTUwYzE0ZGJhNDZiZTYzZWZlY2QyNGJjMTJlYjRjN2I3MGNhODIwNmNjNTFkZDdhYTljYzhmMTA0MTUwYTRjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CUZ0Ua78cuwFW1ZU7_Voekga80Icq95Sm9cV5_Fge9A) 单独调用swagger接口，也返回401错误，是不是需要特殊授权配置？ Curl
> 
> curl -X 'POST' 'https://localhost:44314/api/Folder/folder/6bbf4778-b9b4-417d-87c4-61985648bd77' -H 'accept: application/json' -H 'Content-Type: application/json-patch+json' -d '{ "virtualFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "physicalFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "paths": [ "string" ] }' Request URL https://localhost:44314/api/Folder/folder/6bbf4778-b9b4-417d-87c4-61985648bd77 Server response ![搜狗截图20240104112020](https://private-user-images.githubusercontent.com/5188183/294077208-7643c60c-3ee7-409d-934e-a468d874aa69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzQyMTUsIm5iZiI6MTcwNDQzMzkxNSwicGF0aCI6Ii81MTg4MTgzLzI5NDA3NzIwOC03NjQzYzYwYy0zZWU3LTQwOWQtOTM0ZS1hNDY4ZDg3NGFhNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDU1MTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBmNTEwMmI4M2E3NWI5ZmU0NTNjZjUwZGUzM2MyNGY0MDY1N2M1MjlmNmY1YzgxN2E3MTNkMWFiZjk3MzFjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sO9KbsUZDmB5gong6ARueXEF2DhUUydR94WWw0m6Umk)

你需要提供详细的堆栈日志

**Comment by zzti** [comment]
> > ![搜狗截图20240104104609](https://private-user-images.githubusercontent.com/5188183/294076731-000e18d5-b262-42a3-9a5c-99c56fe3d0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzQyMTUsIm5iZiI6MTcwNDQzMzkxNSwicGF0aCI6Ii81MTg4MTgzLzI5NDA3NjczMS0wMDBlMThkNS1iMjYyLTQyYTMtOWE1Yy05OWM1NmZlM2QwY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDU1MTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTUwYzE0ZGJhNDZiZTYzZWZlY2QyNGJjMTJlYjRjN2I3MGNhODIwNmNjNTFkZDdhYTljYzhmMTA0MTUwYTRjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CUZ0Ua78cuwFW1ZU7_Voekga80Icq95Sm9cV5_Fge9A) 单独调用swagger接口，也返回401错误，是不是需要特殊授权配置？ Curl
> > curl -X 'POST' 'https://localhost:44314/api/Folder/folder/6bbf4778-b9b4-417d-87c4-61985648bd77' -H 'accept: application/json' -H 'Content-Type: application/json-patch+json' -d '{ "virtualFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "physicalFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "paths": [ "string" ] }' Request URL https://localhost:44314/api/Folder/folder/6bbf4778-b9b4-417d-87c4-61985648bd77 Server response ![搜狗截图20240104112020](https://private-user-images.githubusercontent.com/5188183/294077208-7643c60c-3ee7-409d-934e-a468d874aa69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzQyMTUsIm5iZiI6MTcwNDQzMzkxNSwicGF0aCI6Ii81MTg4MTgzLzI5NDA3NzIwOC03NjQzYzYwYy0zZWU3LTQwOWQtOTM0ZS1hNDY4ZDg3NGFhNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDU1MTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBmNTEwMmI4M2E3NWI5ZmU0NTNjZjUwZGUzM2MyNGY0MDY1N2M1MjlmNmY1YzgxN2E3MTNkMWFiZjk3MzFjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sO9KbsUZDmB5gong6ARueXEF2DhUUydR94WWw0m6Umk)
> 
> 你需要提供详细的堆栈日志

curl -X 'POST' \
  'https://localhost:44314/api/Folder/folder/3fa85f64-5717-4562-b3fc-2c963f66afa6' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc0ZvbGRlckNyZWF0ZSI6IjEiLCJJc0ZpbGVVcGxvYWQiOiIxIiwiSXNEZWxldGVGaWxlRm9sZGVyIjoiMSIsIklzU2hhcmVkRmlsZUZvbGRlciI6IjEiLCJJc1NlbmRFbWFpbCI6IjEiLCJJc1JlbmFtZUZpbGUiOiIxIiwiSXNEb3dubG9hZEZpbGUiOiIxIiwiSXNDb3B5RmlsZSI6IjEiLCJJc0NvcHlGb2xkZXIiOiIxIiwiSXNNb3ZlRmlsZSI6IjEiLCJJc1NoYXJlZExpbmsiOiIxIiwic3ViIjoiNGIzNTJiMzctMzMyYS00MGM2LWFiMDUtZTM4ZmNmMTA5NzE5IiwiRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJuYmYiOjE3MDQ0NjA1MzYsImV4cCI6MTcwNDUwMzczNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiUFRDVXNlcnMifQ.x-DIMc4TC6cLxI4RVvrNebhDWMURoErh5hUdZoNx9Ko' \
  -H 'Content-Type: application/json-patch+json' \
  -d '{
  "virtualFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "physicalFolderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "paths": [
    "string"
  ]
}'


`System.NullReferenceException: Object reference not set to an instance of an object.
   at Dorisoy.Pan.MediatR.Handlers.AddChildFoldersCommandHandler.GetFolderUserIds(String folderName, Guid parentPhysicalFolderId, Guid parentVirtualFolderId) in E:\dev\Dorisoy.Pan\Src\Dorisoy.Pan.MediatR\Handlers\Folder\AddChildFoldersCommandHandler.cs:line 209
   at Dorisoy.Pan.MediatR.Handlers.AddChildFoldersCommandHandler.Handle(AddChildFoldersCommand request, CancellationToken cancellationToken) in E:\dev\Dorisoy.Pan\Src\Dorisoy.Pan.MediatR\Handlers\Folder\AddChildFoldersCommandHandler.cs:line 139
   at Dorisoy.Pan.MediatR.PipeLineBehavior.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in E:\dev\Dorisoy.Pan\Src\Dorisoy.Pan.MediatR\PipeLineBehavior\ValidationBehavior.cs:line 41
   at Dorisoy.Pan.API.Controllers.Folder.FolderController.CreateFolders(Guid id, AddChildFoldersCommand addChildFoldersCommand) in E:\dev\Dorisoy.Pan\Src\Dorisoy.Pan.API\Controllers\Folder\FolderController.cs:line 108
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc0ZvbGRlckNyZWF0ZSI6IjEiLCJJc0ZpbGVVcGxvYWQiOiIxIiwiSXNEZWxldGVGaWxlRm9sZGVyIjoiMSIsIklzU2hhcmVkRmlsZUZvbGRlciI6IjEiLCJJc1NlbmRFbWFpbCI6IjEiLCJJc1JlbmFtZUZpbGUiOiIxIiwiSXNEb3dubG9hZEZpbGUiOiIxIiwiSXNDb3B5RmlsZSI6IjEiLCJJc0NvcHlGb2xkZXIiOiIxIiwiSXNNb3ZlRmlsZSI6IjEiLCJJc1NoYXJlZExpbmsiOiIxIiwic3ViIjoiNGIzNTJiMzctMzMyYS00MGM2LWFiMDUtZTM4ZmNmMTA5NzE5IiwiRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJuYmYiOjE3MDQ0NjA1MzYsImV4cCI6MTcwNDUwMzczNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiUFRDVXNlcnMifQ.x-DIMc4TC6cLxI4RVvrNebhDWMURoErh5hUdZoNx9Ko
Connection: close
Content-Length: 156
Content-Type: application/json-patch+json
Cookie: Hm_lvt_5819d05c0869771ff6e6a81cdec5b2e8=1692968724; .AspNetCore.Identity.Application=CfDJ8M-u-xH7jN9GjgJIw01dhPMcHwsuKmUciPE8Gw9W1vl8RQ79lu4J884INPPf9KKmZB39LzUEt3Xh8oC0p_clrHIhSNJdg1YSLI-L1lShsHf6-0UeClkWiIbzIveSEaAE5oJhHG84riU4phlkRv8rSkt9y-DpSyd7OZI6ca2GsX22qn2eYTbOeGGufNqXbCn2kzZyAyrtjace3yqT9HmB9jdEtT8RzLJ7H6vxdCbarvqz4nFHaPig1TG7JTEm1rN5rUQp-HAiV8AxXUTJLo-A-NpH08egeGn9p9GV5Alc7R1tdsUDxUySB9OeTJ5K5EVWBzQN94OgHhRe1k_xvG4K_kkv31f9MTnW7G63iwGyouSnGmyUVdhY60-7dZJkanwZesY71Sezm10wiri6AldLYV3QMmQ51Xdcf02iuJZfh8B2DFQt6lz98GcHhBcdDlKvn9jjyXJSfaxrL1xkHbXFaUlx5chFgNTedEGptVR7D_NE2Su8NNyx-CJx3ZLGt6slgBRqYqooGIEtRN59nhuQXKrSXOPq5UL0LzJg5_gwXuU7rdh69LLImQDK_If4l49TkC-WcH2pTAG1zn03JmJdUheoSpdWXtOl0ZshjtTcTEMuehpUNgr_7L31pEHp0JO9SqRcQLuXGFE755UwAgJK0uDcd8JMHozn50cF939Jv2h3s5uCCEUktGst7KD4EJx-do7hvZEXlvivaNYQkh7xVj2N7vv6hudn74ETUYIDJMI9SDX5LRR8NcBsgdleQHGPz3WYMpVp9lPDyMnNbXDkEuHHqhTlifviQYentK_MMvZAVVxPbwkcjfHRWYBqmdGjanaA9b-0Wk6qFhw7JdDlOuIKghr5VR3NsRc_8hkDTvgvAVtO7-822g3kv7G7fSrJraP0OYxk5eaLYLUPLcO2I3C4by2x2642j4ihe1VC9pb0n-pSP-_oqKO6lQPAbJ8MqdmiZYGhhkUdfyBfZ5Ik_aPzC2zQpcw85OdFjXMd8PykIPIrEn4B8hRPUs7CTmEEyvF3Yu5vf1TJQ0MOrRtdVj1UVGJ6Id8M4qN5Tw5vbnUKig9kNQ29CqBzrxg1-40zvu1Tq-oHowTeLfdYwmz7L1t3A7wk5mnQRy081KIeWcgp
Host: localhost:44314
Referer: https://localhost:44314/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"
dnt: 1
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
origin: https://localhost:44314
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty`
